// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqfxP_RMfwSSDB28nT0MC8F5opT1uOrGw',
    appId: '1:815142586286:web:67acb4f359132e3a1aea3f',
    messagingSenderId: '815142586286',
    projectId: 'hacknarok-spejsy',
    authDomain: 'hacknarok-spejsy.firebaseapp.com',
    storageBucket: 'hacknarok-spejsy.appspot.com',
    measurementId: 'G-NYM6926BEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP0_ShWw1YDOPjyh_J3lZanTeCCZpUNI8',
    appId: '1:815142586286:android:fc240d53c1112e6f1aea3f',
    messagingSenderId: '815142586286',
    projectId: 'hacknarok-spejsy',
    storageBucket: 'hacknarok-spejsy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBAGoe4r9SHnmlOK4spWdjA1LUbCCL1qY',
    appId: '1:815142586286:ios:f489044de37ca10c1aea3f',
    messagingSenderId: '815142586286',
    projectId: 'hacknarok-spejsy',
    storageBucket: 'hacknarok-spejsy.appspot.com',
    iosClientId: '815142586286-ugaibnktktjpv76pteul1kls5hhuqa2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.hacknarok2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBAGoe4r9SHnmlOK4spWdjA1LUbCCL1qY',
    appId: '1:815142586286:ios:f489044de37ca10c1aea3f',
    messagingSenderId: '815142586286',
    projectId: 'hacknarok-spejsy',
    storageBucket: 'hacknarok-spejsy.appspot.com',
    iosClientId: '815142586286-ugaibnktktjpv76pteul1kls5hhuqa2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.hacknarok2023',
  );
}
